
export const LOGIN_REDUCER_CALL = "LOGIN_REDUCER_CALL";
export const REGISTER_REDUCER_CALL = "REGISTER_REDUCER_CALL";
export const REGISTER_SESSION_CALL = "REGISTER_SESSION_CALL";
export const CLOSE_SESSION_CALL = "CLOSE_SESSION_CALL";

export const LISTA_PRODUCTOS_REDUCER_CALL = "LISTA_PRODUCTOS_REDUCER_CALL";
export const LISTA_PRODUCTOS_REDUCER_ADD = "LISTA_PRODUCTOS_REDUCER_ADD";
export const PRODUCTO_GET_REDUCER_CALL = "PRODUCTO_GET_REDUCER_CALL";
export const PRODUCTO_GET_CREATE_REDUCER_CALL = "PRODUCTO_GET_CREATE_REDUCER_CALL";
export const PRODUCTO_GET_REDUCER_ADD = "PRODUCTO_GET_REDUCER_ADD";
export const PRODUCTO_CREAR_REDUCER_CALL = "PRODUCTO_CREAR_REDUCER_CALL";
export const PRODUCTO_ACTUALIZAR_REDUCER_CALL = "PRODUCTO_ACTUALIZAR_REDUCER_CALL";
export const PRODUCTO_ELIMINAR_REDUCER_CALL = "PRODUCTO_ELIMINAR_REDUCER_CALL";


export const LISTA_PROVEEDOR_REDUCER_CALL = "LISTA_PROVEEDOR_REDUCER_CALL";
export const LISTA_PROVEEDOR_REDUCER_ADD = "LISTA_PROVEEDOR_REDUCER_ADD";
export const PROVEEDOR_GET_REDUCER_CALL = "PROVEEDOR_GET_REDUCER_CALL";
export const PROVEEDOR_GET_CREATE_REDUCER_CALL = "PROVEEDOR_GET_CREATE_REDUCER_CALL";
export const PROVEEDOR_GET_REDUCER_ADD = "PROVEEDOR_GET_REDUCER_ADD";
export const PROVEEDOR_CREAR_REDUCER_CALL = "PROVEEDOR_CREAR_REDUCER_CALL";
export const PROVEEDOR_ACTUALIZAR_REDUCER_CALL = "PROVEEDOR_ACTUALIZAR_REDUCER_CALL";
export const PROVEEDOR_ELIMINAR_REDUCER_CALL = "PROVEEDOR_ELIMINAR_REDUCER_CALL";


export const LISTA_CATEGORIAPRODUCTO_REDUCER_CALL = "LISTA_CATEGORIAPRODUCTO_REDUCER_CALL";
export const LISTA_CATEGORIAPRODUCTO_REDUCER_ADD = "LISTA_CATEGORIAPRODUCTO_REDUCER_ADD";
export const CATEGORIAPRODUCTO_GET_REDUCER_CALL = "CATEGORIAPRODUCTO_GET_REDUCER_CALL";
export const CATEGORIAPRODUCTO_GET_CREATE_REDUCER_CALL = "CATEGORIAPRODUCTO_GET_CREATE_REDUCER_CALL";
export const CATEGORIAPRODUCTO_GET_REDUCER_ADD = "CATEGORIAPRODUCTO_GET_REDUCER_ADD";
export const CATEGORIAPRODUCTO_CREAR_REDUCER_CALL = "CATEGORIAPRODUCTO_CREAR_REDUCER_CALL";
export const CATEGORIAPRODUCTO_ACTUALIZAR_REDUCER_CALL = "CATEGORIAPRODUCTO_ACTUALIZAR_REDUCER_CALL";
export const CATEGORIAPRODUCTO_ELIMINAR_REDUCER_CALL = "CATEGORIAPRODUCTO_ELIMINAR_REDUCER_CALL";